name: deploy to lambda

on:
  push:
    branches:
      - master
jobs:
  deploy_source:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Client Package
        run: |
          npm install
          npm run build
        working-directory: booking/client
      - name: Server Package Install
        run: |
          npm install
        working-directory: booking/server
      - name: zip
        run: |
          ./package.sh
        working-directory: booking/server
      - name: Lambda Upload
        run: |
          aws lambda update-function-code --function-name getBooking-4f4ac4b --zip-file fileb://dist/function.zip
        working-directory: booking/server
